#!/usr/bin/env sh

ed ()
{
	file="$(fzf)"
	[[ ! -z "$file" ]] && vim "$file"
}

setup()
{
	set -xe
	rm -rf ~/Desktop ~/Templates ~/Music ~/Projects ~/Public
	ln -sf /mnt/5tb/Music $HOME/Music
	[[ ! -d "$HOME/VirtualBox VMs" ]] && ln -sf /mnt/1tb/Vbox_Vms "$HOME/VirtualBox VMs"
	[[ ! -d "$HOME/Programming" ]] && ln -sf /mnt/5tb/Programming $HOME/Programming
	[[ ! -d "$HOME/.config/mozilla" ]] && ln -sf /mnt/1tb/BrowserData/mozilla $HOME/.config
	[[ ! -d "$HOME/.config/chromium" ]] && ln -sf /mnt/1tb/BrowserData/chromium $HOME/.config
	set +xe
	curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
}

install_pkgs()
{
	set -xe
	sudo pacman -Sy i3 i3status alacritty virtualbox virtualbox-host-dkms virtualbox-guest-iso \
		gvfs gvfs-smb gvfs-nfs thunar vim terminology rofi git ttf-liberation ttf-0xproto-nerd \
		noto-fonts noto-fonts-cjk noto-fonts-extra noto-fonts-emoji fzf bash-completion \
		clang playerctl openssh ttf-inconsolata xwallpaper picom dunst gnome-keyring exa man --noconfirm

	sudo pacman -S 86kbyte/ungoogled-chromium 86kbyte/yay-bin --noconfirm
	set +xe
}

licence_mit()
{
	cat << EOF > LICENCE
MIT License

Copyright (c) $(date +'%Y') mawpz

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
EOF
}

# Standard Aliases
alias \
	ls='exa --color=auto' \
	ll="ls -l" \
	lah="ls -lah" \
	grep='grep --color=auto' \
	nossvr="xset s off; xset s noblank; xset -dpms" \
	rm="rm -i" \
	pac="sudo pacman" \
	so="source" \
	cal="cal -m -3" \
	rld="source ~/.config/shell/aliasrc"

# Directory Shortcuts
alias \
	gvfsmnt="/run/user/1000/gvfs/" \
	8tb="/run/user/1000/gvfs/smb-share:server=10.0.0.1,share=8tb" \
	120g="/mnt/120g" \
	1tb="/mnt/1tb" \
	4tb="/mnt/4tb" \
	5tb="/mnt/5tb" \
	code="/mnt/5tb/code"
