db_file			"~/.config/mpd/db"
music_directory		"~/Music"
auto_update		"yes"
playlist_directory	"~/.config/mpd/playlists"

audio_output {
	type		"alsa"
	name		"ALSA Sound Card"
}

audio_output {
	type 		"pulse"
	name 		"PulseAudio"
	sink		"alsa_output.usb-Creative_Technology_Ltd_Sound_Blaster_Play__3_YDSB1730602002716G-00.analog-stereo"
}

audio_output {
	type 		"fifo"
	name 		"FIFO (for ncmpcpp visualisation)"
	path		"/tmp/mpd.fifo"
	format		"44100:16:2"
}
